import 'package:flutter/foundation.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/price_report.dart';

class PriceReportService {
  static final PriceReportService instance = PriceReportService._();
  PriceReportService._();

  final _supabase = Supabase.instance.client;

  /// Submit a new price report
  Future<bool> submitReport({
    required String medicineName,
    required double pricePaid,
    int? medicineId,
    double? mrp,
    String? pharmacyName,
    String? locationArea,
  }) async {
    final user = _supabase.auth.currentUser;
    if (user == null) {
      debugPrint('Error: User must be logged in to report price.');
      return false;
    }

    try {
      final report = PriceReport(
        id: '', // Generated by DB
        userId: user.id,
        medicineName: medicineName,
        medicineId: medicineId,
        pricePaid: pricePaid,
        mrp: mrp,
        pharmacyName: pharmacyName,
        locationArea: locationArea,
        createdAt: DateTime.now(), // Ignored by DB
      );

      await _supabase.from('price_reports').insert(report.toMap());
      return true;
    } catch (e) {
      debugPrint('Failed to submit price report: $e');
      return false;
    }
  }

  /// Get reports for a specific medicine
  Future<List<PriceReport>> getReportsForMedicine(String medicineName) async {
    try {
      final response = await _supabase
          .from('price_reports')
          .select()
          .eq('medicine_name', medicineName)
          .order('created_at', ascending: false)
          .limit(10);

      final List<dynamic> data = response;
      return data.map((json) => PriceReport.fromMap(json)).toList();
    } catch (e) {
      debugPrint('Failed to fetch reports: $e');
      return [];
    }
  }

  /// Get the average street price for a medicine
  Future<double?> getAveragePrice(String medicineName) async {
    try {
      final response = await _supabase
          .rpc('get_average_price', params: {'medicine_name_param': medicineName});
      
      if (response == null) return null;
      return (response as num).toDouble();
    } catch (e) {
      // If RPC fails or doesn't exist, we can fallback to client-side calc
      // but simpler to return null for now
      return null;
    }
  }
}
